version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  database:
    image: postgres
    container_name: app_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=app
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-network

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - app-network

volumes:
  pgdata:
    driver: local