export const CHARACTERS_LOADING = "CHARACTERS_LOADING";
export const CHARACTERS_SUCCESS = "CHARACTERS_SUCCESS";
export const CHARACTERS_ERROR = "CHARACTERS_ERROR";

export const FILMS_LOADING = "FILMS_LOADING";
export const FILMS_SUCCESS = "FILMS_SUCCESS";
export const FILMS_ERROR = "FILMS_ERROR";

export const SPECIES_LOADING = "SPECIES_LOADING";
export const SPECIES_SUCCESS = "SPECIES_SUCCESS";
export const SPECIES_ERROR = "SPECIES_ERROR";

export const SEARCH_CHARACTERS = "SEARCH_CHARACTERS";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
