export const CHARACTERS_LOADING = "CHARACTERS_LOADING";
export const CHARACTERS_SUCCESS = "CHARACTERS_SUCCESS";
export const CHARACTERS_ERROR = "CHARACTERS_ERROR";

export const FILMS_LOADING = "FILMS_LOADING";
export const FILMS_SUCCESS = "FILMS_SUCCESS";
export const FILMS_ERROR = "FILMS_ERROR";

export const SPECIES_LOADING = "SPECIES_LOADING";
export const SPECIES_SUCCESS = "SPECIES_SUCCESS";
export const SPECIES_ERROR = "SPECIES_ERROR";

export const VEHICLES_LOADING = "VEHICLES_LOADING";
export const VEHICLES_SUCCESS = "VEHICLES_SUCCESS";
export const VEHICLES_ERROR = "VEHICLES_ERROR";

export const STARSHIPS_LOADING = "STARSHIPS_LOADING";
export const STARSHIPS_SUCCESS = "STARSHIPS_SUCCESS";
export const STARSHIPS_ERROR = "STARSHIPS_ERROR";

export const PLANETS_LOADING = "PLANETS_LOADING";
export const PLANETS_SUCCESS = "PLANETS_SUCCESS";
export const PLANETS_ERROR = "PLANETS_ERROR";

export const SEARCH_CHARACTERS = "SEARCH_CHARACTERS";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
